services:
  localstack:
    image: localstack/localstack:latest
    container_name: garden-club-localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3,dynamodb,apigateway,lambda
      - DEBUG=0
      - LAMBDA_EXECUTOR=docker-reuse
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_ACKNOWLEDGE_ACCOUNT_REQUIREMENT=1
    volumes:
      - localstack_data:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - localstack_default

volumes:
  localstack_data:

networks:
  localstack_default:
    driver: bridge
